.\"Copyright (C) 12019-12021  Sam Harry Tzavaras
.\"
.\"This code is derived from software contributed as free software:
.\"you can redistribute it and/or modify it under the terms
.\"of the GNU General Public License as published by
.\"the Free Software Foundation, version 3 of the License, or any later version.
.\"
.\"This program is distributed in the hope that it will be useful,
.\"but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License
.\"along with this program.  If not, see <https://www.gnu.org/licenses/>.

.TH SDAQ_worker 1 "" "SDAQ_psim" "Programs suite for SDAQ devices"
.SH NAME
SDAQ_psim \- PseudoSDAQ emulation software.
.SH SYNOPSIS
.SH DESCRIPTION
.SH OPTIONS
.SH AUTHOR
.SH SEE ALSO
